from enum import Enum


class MessageCode(Enum):
    FORBIDDEN = "FORBIDDEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    USER_EXISTS = "USER_EXITS"
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    SUCCESS = "SUCCESS"
    FAIL = "FAIL"
    ROLE_NOT_SUPPORTED = "ROLE_NOT_SUPPORTED"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    REFUND_SUCCESS = "REFUND_SUCCESS"
    REFUND_PENDING = "REFUND_PENDING"
    REFUND_FAILED = "REFUND_FAILED"

    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    ALREADY_PAID = "ALREADY_PAID"

    INVALID_DATA = "INVALID_DATA"
    ALREADY_REFUNDED = "ALREADY_REFUNDED"



STATUS_MAP = {
    MessageCode.SUCCESS: 200,
    MessageCode.FAIL: 400,
    MessageCode.INVALID_DATA: 400,

    MessageCode.USER_EXISTS: 409,
    MessageCode.USER_NOT_FOUND: 404,

    MessageCode.INVALID_CREDENTIALS: 401,

    MessageCode.UNAUTHORIZED: 401,
    MessageCode.FORBIDDEN: 403,

    MessageCode.ROLE_NOT_SUPPORTED: 400,

    # PAYMENT
    MessageCode.PAYMENT_SUCCESS: 200,
    MessageCode.PAYMENT_PENDING: 202,
    MessageCode.PAYMENT_FAILED: 400,

    MessageCode.REFUND_SUCCESS: 200,
    MessageCode.REFUND_PENDING: 202,
    MessageCode.REFUND_FAILED: 400,

    MessageCode.TRANSACTION_NOT_FOUND: 404,
    MessageCode.ALREADY_PAID: 409,
    MessageCode.ALREADY_REFUNDED: 409,

    MessageCode.INVALID_SIGNATURE: 400,
}