from enum import Enum


class MessageCode(Enum):
    USER_EXITS = "USER_EXITS"
    REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    SUCCESS = "SUCCESS"
    FAIL = "FAIL"
    ROLE_NOT_SUPPORTED = "ROLE_NOT_SUPPORTED"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    REFUND_SUCCESS = "REFUND_SUCCESS"
    REFUND_PENDING = "REFUND_PENDING"
    REFUND_FAILED = "REFUND_FAILED"

    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND"
    ALREADY_PAID = "ALREADY_PAID"

    INVALID_DATA = "INVALID_DATA"
    ALREADY_REFUNDED = "ALREADY_REFUNDED"

