from enum import Enum


class ScheduleStatus(Enum):
    ACTIVE = "ACTIVE"

    LEAVE_PENDING = "LEAVE_PENDING"
    LEAVE_APPROVED = "LEAVE_APPROVED"
    LEAVE_REJECTED = "LEAVE_REJECTED"

    EXTRA_PENDING = "EXTRA_PENDING"
    EXTRA_APPROVED = "EXTRA_APPROVED"
    EXTRA_REJECTED = "EXTRA_REJECTED"

    WEEKEND_PENDING = "WEEKEND_PENDING"
    WEEKEND_APPROVED = "WEEKEND_APPROVED"
    WEEKEND_REJECTED = "WEEKEND_REJECTED"


class ScheduleType(Enum):
    REGULAR = "REGULAR"
    EXTRA_SHIFT = "EXTRA_SHIFT"
    WEEKEND_SHIFT = "WEEKEND_SHIFT"