"""add field consultation_fee

Revision ID: 120536bc6db4
Revises: 2e280aeb21ea
Create Date: 2026-04-23 00:21:43.898546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120536bc6db4'
down_revision = '2e280aeb21ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consultation_fee', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_specialties', schema=None) as batch_op:
        batch_op.drop_column('consultation_fee')

    # ### end Alembic commands ###
