"""refactor data type embeding

Revision ID: 1903eafb96b3
Revises: b27ad485832b
Create Date: 2026-04-28 21:16:27.910488

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '1903eafb96b3'
down_revision = 'b27ad485832b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('embedding',
                              existing_type=sa.TEXT(),
                              type_=Vector(1536),
                              postgresql_using="embedding::vector(1536)",
                              existing_nullable=True)
        batch_op.create_index('ix_doctors_embedding', ['embedding'], unique=False, postgresql_using='ivfflat',
                              postgresql_ops={'embedding': 'vector_cosine_ops'})

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('embedding',
                              existing_type=sa.TEXT(),
                              type_=Vector(1536),
                              postgresql_using="embedding::vector(1536)",
                              existing_nullable=True)
        batch_op.create_index('ix_specialties_embedding', ['embedding'], unique=False, postgresql_using='ivfflat',
                              postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})

    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.alter_column('embedding',
                              existing_type=sa.TEXT(),
                              type_=Vector(1536),
                              postgresql_using="embedding::vector(1536)",
                              existing_nullable=True)
        batch_op.create_index('ix_symptoms_embedding', ['embedding'], unique=False, postgresql_using='ivfflat',
                              postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_index('ix_symptoms_embedding', postgresql_using='ivfflat',
                            postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
        batch_op.alter_column('embedding',
                              existing_type=Vector(1536),
                              type_=sa.TEXT(),
                              postgresql_using="embedding::vector(1536)",
                              existing_nullable=True)

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index('ix_specialties_embedding', postgresql_using='ivfflat',
                            postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
        batch_op.alter_column('embedding',
                              existing_type=Vector(1536),
                              type_=sa.TEXT(),
                              postgresql_using="embedding::vector(1536)",
                              existing_nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index('ix_doctors_embedding', postgresql_using='ivfflat',
                            postgresql_ops={'embedding': 'vector_cosine_ops'})
        batch_op.alter_column('embedding',
                              existing_type=Vector(1536),
                              type_=sa.TEXT(),
                              postgresql_using="embedding::vector(1536)",
                              existing_nullable=True)

    # ### end Alembic commands ###
