"""add field avatar_url

Revision ID: 36746f81d920
Revises: 120536bc6db4
Create Date: 2026-04-23 21:03:09.355980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36746f81d920'
down_revision = '120536bc6db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
