"""refactor data type embeding

Revision ID: 81d175b282b8
Revises: 1903eafb96b3
Create Date: 2026-04-28 22:48:14.274026

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '81d175b282b8'
down_revision = '1903eafb96b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(1536),
               type_=Vector(768),
               existing_nullable=True)

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(1536),
               type_=Vector(768),
               existing_nullable=True)

    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(1536),
               type_=Vector(768),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(768),
               type_=Vector(1536),
               existing_nullable=True)

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(768),
               type_=Vector(1536),
               existing_nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(768),
               type_=Vector(1536),
               existing_nullable=True)

    # ### end Alembic commands ###
