"""refactor appoinment add field

Revision ID: a3350311877c
Revises: bcc9ccd31cea
Create Date: 2026-05-08 22:12:36.589236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3350311877c'
down_revision = 'bcc9ccd31cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symptom', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('symptom')

    # ### end Alembic commands ###
