"""refactor schedule add field

Revision ID: bcc9ccd31cea
Revises: cf5dffad81ed
Create Date: 2026-05-03 23:24:22.033554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc9ccd31cea'
down_revision = 'cf5dffad81ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_schedules', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('status')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
