"""refactor relation sympromt specialty

Revision ID: cf5dffad81ed
Revises: d556e689e193
Create Date: 2026-04-29 08:15:20.532266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5dffad81ed'
down_revision = 'd556e689e193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_specialties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_symptom_specialties_specialty_id'), ['specialty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_symptom_specialties_symptom_id'), ['symptom_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptom_specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptom_specialties_symptom_id'))
        batch_op.drop_index(batch_op.f('ix_symptom_specialties_specialty_id'))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
