"""refactor size embeding 3072

Revision ID: d556e689e193
Revises: 81d175b282b8
Create Date: 2026-04-28 23:28:32.198246

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'd556e689e193'
down_revision = '81d175b282b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(768),
               type_=Vector(3072),
               existing_nullable=True)
        # batch_op.drop_index(batch_op.f('ix_doctors_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(768),
               type_=Vector(3072),
               existing_nullable=True)
        # batch_op.drop_index(batch_op.f('ix_specialties_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=Vector(768),
               type_=Vector(3072),
               existing_nullable=True)
        # batch_op.drop_index(batch_op.f('ix_symptoms_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptoms_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
        batch_op.alter_column('embedding',
               existing_type=Vector(3072),
               type_=Vector(768),
               existing_nullable=True)

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
        batch_op.alter_column('embedding',
               existing_type=Vector(3072),
               type_=Vector(768),
               existing_nullable=True)

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')
        batch_op.alter_column('embedding',
               existing_type=Vector(3072),
               type_=Vector(768),
               existing_nullable=True)

    # ### end Alembic commands ###
