"""refactor db

Revision ID: fa1d319e8809
Revises: a3350311877c
Create Date: 2026-05-20 13:12:45.483811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1d319e8809'
down_revision = 'a3350311877c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointments_time_slot_id_key'), type_='unique')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symptoms_embedding'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symptoms_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_embedding'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='ivfflat')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('appointments_time_slot_id_key'), ['time_slot_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
